"""Add missing user columns

Revision ID: 1067bf439f99
Revises: 9e84743a2854
Create Date: 2026-06-07 18:33:37.089378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1067bf439f99'
down_revision: Union[str, None] = '9e84743a2854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_evaluate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_investigate', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('can_approve_resolution', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_approve_resolution')
    op.drop_column('users', 'can_investigate')
    op.drop_column('users', 'can_evaluate')
    # ### end Alembic commands ###
