"""add_multi_tenant_and_multi_department

Revision ID: 24bc0d8326de
Revises: 53f41691217a
Create Date: 2026-06-05 18:11:48.514188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bc0d8326de'
down_revision: Union[str, None] = '53f41691217a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'SUPER_ADMIN'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'ORG_ADMIN'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'DEPT_HEAD'")
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('HR', 'CMD', 'NORMAL', name='departmenttype'), nullable=False),
    sa.Column('head_user_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['head_user_id'], ['users.id'], name='fk_dept_head_user', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_tenant_id'), 'invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.add_column('complaints', sa.Column('employee_department_id', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('primary_department_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'departments', ['employee_department_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'departments', ['primary_department_id'], ['id'])
    op.add_column('tenants', sa.Column('status', sa.String(length=50), server_default='Active', nullable=False))
    op.add_column('tenants', sa.Column('timezone', sa.String(length=100), server_default='Asia/Kolkata', nullable=False))
    op.add_column('tenants', sa.Column('working_hours', sa.JSON(), nullable=True))
    op.add_column('tenants', sa.Column('logo_url', sa.String(length=1000), nullable=True))
    op.add_column('tenants', sa.Column('industry', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('address', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('department_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('can_assign_complaints', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('can_resolve_complaints', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('can_view_hr_sensitive', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'can_view_hr_sensitive')
    op.drop_column('users', 'can_resolve_complaints')
    op.drop_column('users', 'can_assign_complaints')
    op.drop_column('users', 'department_id')
    op.drop_column('tenants', 'address')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'industry')
    op.drop_column('tenants', 'logo_url')
    op.drop_column('tenants', 'working_hours')
    op.drop_column('tenants', 'timezone')
    op.drop_column('tenants', 'status')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'primary_department_id')
    op.drop_column('complaints', 'employee_department_id')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_tenant_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
