"""add_clustering_and_valuable_fields

Revision ID: 53f41691217a
Revises: d4a33eb90226
Create Date: 2026-06-03 08:48:21.216904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f41691217a'
down_revision: Union[str, None] = 'd4a33eb90226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('is_repeated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('complaints', sa.Column('repeat_count_at_assignment', sa.Integer(), server_default='0', nullable=False))
    op.add_column('complaints', sa.Column('similarity_score', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('is_valuable', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('complaints', sa.Column('ai_value_reason', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('is_within_sla', sa.Boolean(), nullable=True))
    op.add_column('complaints', sa.Column('first_resolved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'first_resolved_at')
    op.drop_column('complaints', 'is_within_sla')
    op.drop_column('complaints', 'ai_value_reason')
    op.drop_column('complaints', 'is_valuable')
    op.drop_column('complaints', 'similarity_score')
    op.drop_column('complaints', 'repeat_count_at_assignment')
    op.drop_column('complaints', 'is_repeated')
    # ### end Alembic commands ###
