"""initial_schema

Revision ID: 9c3b7a5ad5c5
Revises: 
Create Date: 2026-05-31 03:44:34.795956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '9c3b7a5ad5c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clusters_tenant_id'), 'clusters', ['tenant_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_tenant_id'), 'tags', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('EMPLOYEE', 'CMD', 'HR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('primary_department', sa.String(length=255), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('is_hr_sensitive', sa.Boolean(), nullable=False),
    sa.Column('ai_categorization_reason', sa.Text(), nullable=True),
    sa.Column('ai_priority_reason', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SOLVED', 'REJECTED', 'WITHDRAWN', 'EXPIRED', name='complaintstatus'), nullable=False),
    sa.Column('priority_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_source', sa.Enum('AI', 'MANUAL', 'RULE', name='prioritysource'), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('sla_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cluster_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_employee_id'), 'complaints', ['employee_id'], unique=False)
    op.create_index('ix_complaints_sla_due', 'complaints', ['sla_due_at'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_index('ix_complaints_tenant_dept', 'complaints', ['tenant_id', 'primary_department'], unique=False)
    op.create_index(op.f('ix_complaints_tenant_id'), 'complaints', ['tenant_id'], unique=False)
    op.create_index('ix_complaints_tenant_status', 'complaints', ['tenant_id', 'status'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint_attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_safe', sa.Boolean(), nullable=False),
    sa.Column('ocr_status', sa.String(length=20), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_attachments_complaint_id'), 'complaint_attachments', ['complaint_id'], unique=False)
    op.create_table('complaint_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('actor_user_id', sa.String(), nullable=True),
    sa.Column('action_type', sa.Enum('CREATED', 'STATUS_CHANGE', 'CATEGORY_UPDATE', 'PRIORITY_OVERRIDE', 'ESCALATION_CHANGE', 'ASSIGNMENT_CHANGE', 'VISIBILITY_CHANGE', 'REJECTION_EDIT', 'RESOLUTION_EDIT', 'ATTACHMENT_ADDED', 'NOTE_ADDED', 'RATED', name='auditactiontype'), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_audit_logs_complaint_id'), 'complaint_audit_logs', ['complaint_id'], unique=False)
    op.create_table('complaint_embeddings',
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_table('complaint_tags',
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('complaint_id', 'tag_id')
    )
    op.create_table('internal_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('role_at_time', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_visible_to_employee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_notes_complaint_id'), 'internal_notes', ['complaint_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('COMPLAINT_CREATED', 'COMPLAINT_ASSIGNED', 'COMPLAINT_STARTED', 'COMPLAINT_RESOLVED', 'COMPLAINT_REJECTED', 'COMPLAINT_WITHDRAWN', 'COMPLAINT_RATED', 'ESCALATION_LEVEL_1', 'ESCALATION_LEVEL_2', 'AI_FAILED', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', name='notificationchannel'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('processing_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('task_type', sa.Enum('CATEGORIZATION', 'PRIORITY', 'SIMILARITY', 'SUMMARY_TAGS', 'OCR', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'FAILED', name='queuestatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('permanent_failure', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_queue_complaint_id'), 'processing_queue', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_processing_queue_tenant_id'), 'processing_queue', ['tenant_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_id')
    )
    op.create_table('rejections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('rejected_by_user_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_id')
    )
    op.create_table('resolution_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('complaint_id', sa.String(), nullable=False),
    sa.Column('resolved_by_user_id', sa.String(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('tags_snapshot', sa.JSON(), nullable=True),
    sa.Column('visible_to_employee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resolution_details')
    op.drop_table('rejections')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_processing_queue_tenant_id'), table_name='processing_queue')
    op.drop_index(op.f('ix_processing_queue_complaint_id'), table_name='processing_queue')
    op.drop_table('processing_queue')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_internal_notes_complaint_id'), table_name='internal_notes')
    op.drop_table('internal_notes')
    op.drop_table('complaint_tags')
    op.drop_table('complaint_embeddings')
    op.drop_index(op.f('ix_complaint_audit_logs_complaint_id'), table_name='complaint_audit_logs')
    op.drop_table('complaint_audit_logs')
    op.drop_index(op.f('ix_complaint_attachments_complaint_id'), table_name='complaint_attachments')
    op.drop_table('complaint_attachments')
    op.drop_table('notification_preferences')
    op.drop_index('ix_complaints_tenant_status', table_name='complaints')
    op.drop_index(op.f('ix_complaints_tenant_id'), table_name='complaints')
    op.drop_index('ix_complaints_tenant_dept', table_name='complaints')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index('ix_complaints_sla_due', table_name='complaints')
    op.drop_index(op.f('ix_complaints_employee_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_tenant_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_clusters_tenant_id'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_table('tenants')
    # ### end Alembic commands ###
