"""add tenant settings

Revision ID: 9e84743a2854
Revises: 24bc0d8326de
Create Date: 2026-06-05 18:35:16.046653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e84743a2854'
down_revision: Union[str, None] = '24bc0d8326de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_dept_head_user', 'departments', 'users', ['head_user_id'], ['id'], use_alter=True)
    op.add_column('tenants', sa.Column('allow_cmd_view_hr_sensitive', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tenants', sa.Column('allow_cmd_view_hr_sensitive_anonymized', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('tenants', sa.Column('allow_dept_head_view_hr_sensitive', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'allow_dept_head_view_hr_sensitive')
    op.drop_column('tenants', 'allow_cmd_view_hr_sensitive_anonymized')
    op.drop_column('tenants', 'allow_cmd_view_hr_sensitive')
    op.drop_constraint('fk_dept_head_user', 'departments', type_='foreignkey')
    # ### end Alembic commands ###
