"""add_employee_inputs_and_anonymity

Revision ID: cae1b76d06ba
Revises: 9c3b7a5ad5c5
Create Date: 2026-06-01 17:46:21.933188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae1b76d06ba'
down_revision: Union[str, None] = '9c3b7a5ad5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('employee_department', sa.String(length=255), nullable=True))
    op.add_column('complaints', sa.Column('employee_category', sa.String(length=255), nullable=True))
    op.add_column('complaints', sa.Column('employee_subcategory', sa.String(length=255), nullable=True))
    op.add_column('complaints', sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('complaints', sa.Column('visibility_settings', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'visibility_settings')
    op.drop_column('complaints', 'is_anonymous')
    op.drop_column('complaints', 'employee_subcategory')
    op.drop_column('complaints', 'employee_category')
    op.drop_column('complaints', 'employee_department')
    # ### end Alembic commands ###
