"""add_employee_management

Revision ID: d4a33eb90226
Revises: cae1b76d06ba
Create Date: 2026-06-02 16:40:38.369124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a33eb90226'
down_revision: Union[str, None] = 'cae1b76d06ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_update_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.String(length=1000), nullable=True),
    sa.Column('new_value', sa.String(length=1000), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('review_notes', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_update_requests_tenant_id'), 'profile_update_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_profile_update_requests_user_id'), 'profile_update_requests', ['user_id'], unique=False)
    op.add_column('users', sa.Column('employee_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=50), server_default='Active', nullable=False))
    op.add_column('users', sa.Column('designation', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('date_of_joining', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('profile_photo', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_photo')
    op.drop_column('users', 'date_of_joining')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'status')
    op.drop_column('users', 'employee_id')
    op.drop_index(op.f('ix_profile_update_requests_user_id'), table_name='profile_update_requests')
    op.drop_index(op.f('ix_profile_update_requests_tenant_id'), table_name='profile_update_requests')
    op.drop_table('profile_update_requests')
    # ### end Alembic commands ###
